### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by QuantJia** [kimoktm/Face2face#3]
Thks the author job! 

I play the python cli/processBFM2017.py the cli, get the error:
Traceback (most recent call last):
  File "cli/processBFM2017.py", line 87, in <module>
    processBFM2017('./models/model2017-1_bfm_nomouth.h5', '')
  File "cli/processBFM2017.py", line 76, in processBFM2017
    vertex2face = np.array([np.where(np.isin(face, vertexInd).any(axis = 0))[0] for vertexInd in range(numVertices)])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (53149,) + inhomogeneous part.

I tried the ./models/model2017-1_face12_nomouth.h5 and ./models/model2017-1_bfm_nomouth.h5, the same error occured.

**Comment by mimic-jmittig** [comment]
I'm running into the same issue right now. Did you find any solution?
I tried the model2017-1_face12_nomouth.h5 and a new one from 2019 (model2019_face12.h5)

**Comment by kimoktm** [comment]
I pushed a fix, please try and let me know if it still doesn't work
